#!/usr/bin/env bash

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
fi

num=$(cat "$1")
factors=$(factor "$num" | awk -F ':' '{print $2}' | awk '{$1=$1};1' OFS='*')
echo "$num=$factors"
